version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  pre_build:
    commands:
       - echo "Package Artifact"
      #- echo Code Scanning using SonarQube
      #- mvn verify sonar:sonar
      #- echo Publish Artifact To JFROG  
  build:
    commands:
      - echo Build started on `date`
      - pwd
      - ls -lrta
      #- ls -lrt $CODEBUILD_SRC_DIR/settings.xml
      #- cp -pvr $CODEBUILD_SRC_DIR/settings.xml ~/.m2/settings.xml
      #- echo Publish Artifact To JFROG based on the User Input in POM.xml file 
      - mvn clean
      - echo "Deliver Artifact To Tomcat & Deploy"
      - aws s3 cp s3://8amcloudbinary/devops.war /usr/share/tomcat/webapps/devops.war
      #- sh 'curl -u admin:redhat@123 -T target/**.war "http://44.211.143.213:8080/manager/text/deploy?path=/b78am&update=true"'
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/b78am.war
